### ISSUE TITLE
patch.exe raises UAC prompt

### ISSUE THREAD

**Issue by pageer** [Komodo/SideBySideDiff#1]
The bundled patch.exe that is used for Windows doesn't run properly.  This renders SideBySideDiff completely unusable on most modern Windows configurations.

When trying to display a side-by-side diff, Windows will pop up a UAC prompt for patch.exe.  If the user approves the execution, patch.exe will open a console window and just hang with no output.  I'm guessing that the privilege escalation is somehow causing the inter-process communication to break down.

Note that there's no reason that patch.exe actually _needs_ administrator access.  It's just that the heuristic that Windows uses to detect setup programs thinks that the file name means it's an installer and asks for escalation.

I'm able to resolve the problem and use the extension normally if I rename patch.exe to something that _doesn't_ look like an installer, such as "ptch.exe", and update sbs_diff_helper.py accordingly.  (Note that just making a symlink to patch.exe will not do the trick.)  The other option would be to create a manifest file for patch.exe (which would be more complicated and probably not worth the effort, as the only actual problem seems to be the name).

**Comment by toddw-as** [comment]
Yes, silly Windows. Could you try using the "patch.exe" and "patch.exe.manifest" from:
https://github.com/Komodo/KomodoEdit/tree/trunk/mozilla/bin-win32

We ran into this problem for the Komodo build machines and had to go the manifest route...

**Comment by pageer** [comment]
Nice!  That works just fine.  I dropped those in the platform/WINNT directory and now there's no UAC prompt and the diff generates as expected.  Gotta love it when there's already a fix handy.
